#!/bin/bash

# apply formatter and import
goimports() {
	docker run --rm -v $(pwd):/data cytopia/goimports -w .
}

# build go files
build() {
	go build -o shiba *.go
}

# run go test
gotest() {
	clean
	build
	mkdir -p tests
	go test ./...
}

# cleanup files
clean() {
	rm -f shiba tests/*
}

# shows the help
help() {
	echo "usage:"
	grep -B 1 '^.*() {$' task | awk 'BEGIN {FS="\n"; RS="--\n"} {sub("\(\) {", "", $2); sub("# ", "", $1); printf("\t\033[36m%-20s\033[m %s\n", $2, $1)}'
}

target=$1
if [ -z "$target" ]; then
	help
	exit 0
fi

$target
