name: Release

on:
  workflow_dispatch:

jobs:
  releaes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compute the upcoming version from the current latest version
        run: |
          cur_ver=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/hidetatz/shiba.git 'v*.*.*' | tail --lines=1 | cut --delimiter='/' --fields=3)
          echo $cur_ver
          # This increments the patch version
          # https://stackoverflow.com/questions/6245293/extract-version-number-from-file-in-shell-script
          next_ver="${cur_ver%.*}.$((${cur_ver##*.}+1))"
          echo $next_ver
          # - name: build files
          #   run: |
          # 　　tar zxf ~/Downloads/shiba0.0.1.linux_amd64.tar.gz
          # - uses: softprops/action-gh-release@v1
